# Generated by Django 5.0.2 on 2024-02-26 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bib_app', '0002_remove_utilisateur_adresse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='adresse',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='code_postal',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='telephone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='ville',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
