# Generated by Django 5.0.2 on 2024-02-26 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bib_app', '0003_utilisateur_adresse_utilisateur_code_postal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='adresse',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='code_postal',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='date_naissance',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='telephone',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='ville',
        ),
    ]
