# Generated by Django 5.0.2 on 2024-02-26 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('bib_app', '0004_remove_utilisateur_adresse_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Utilisateur',
            new_name='Users',
        ),
    ]
